# Paths
class_model_checkpoint: "path_to_resnet"
policy_model_checkpoint: "path_to_logs_and_saved_models"
recons_model_checkpoint: "path_to_promptmr"

# Data & model dimensions
resolution: 320
num_layers: 4
num_chans: 16
fc_size: 256

# Training hyperparameters
batch_size: 128
val_batch_size: 128
replay_buffer_size: 300000
minibatch_size: 128
target_update_freq: 1
start_minibatch: 10000

# Runtime
num_workers: 12
data_parallel: True
do_train: True
train_resnet: False
a_steps: 1
r_steps: 1
num_epochs: 30
device: "cuda"
budget: 64

# Sampling settings
accelerations:
  - 4
center_fractions:
  - 0.05
sample_rate: 1.0

# Classification
num_classes: 2
drop_prob: 0.1
seed: 45
lr: 0.0001
lr_step_size: 8
lr_gamma: 0.5

# Reconstruction
num_cascades: 12
num_adj_slices: 3
n_feat0: 48
feature_dim:
  - 72
  - 96
  - 120
prompt_dim:
  - 24
  - 48
  - 72
sens_n_feat0: 24
sens_feature_dim:
  - 36
  - 48
  - 60
sens_prompt_dim:
  - 12
  - 24
  - 36
len_prompt:
  - 5
  - 5
  - 5
prompt_size:
  - 64
  - 32
  - 16
n_enc_cab:
  - 2
  - 3
  - 3
n_dec_cab:
  - 2
  - 2
  - 3
n_skip_cab:
  - 1
  - 1
  - 1
n_bottleneck_cab: 3
